### ISSUE TITLE
Prevent load errors, due to wrong and missing build

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/ft-site-editing#18]
```[tasklist]
### Tasks
- [ ] https://github.com/createwithrani/superlist/issues/40
- [x] Load [alternate version](https://github.com/carstingaxion/superlist) directly from `content/plugins` as a temp. workaround
- [x] Build ~~Fix~~ alternate version
- [x] Remove alternate version
```
